### ISSUE TITLE
Incompatible with OpenKeychain 4.4

### ISSUE THREAD

**Issue by DeX77** [PGPAuth/PGPAuth_Android#18] opened 2017-05-07 19:43 UTC
OpenKeychain raised minimal API version to 7 in commit 85ee12d143c5622981f8879e31b4052b3bf8023a.

PGPAuth doesn't work anymore since then.

**Comment by LittleFox94** [comment] 2017-05-07 21:24
Confirmed - will look into it.
Thanks for reporting :)

**Comment by LittleFox94** [comment] 2017-05-07 22:07
Should get a fix tomorrow (while "tomorrow" is after sleeping and not after 0am)

**Comment by LittleFox94** [comment] 2017-05-08 16:03
[pgpauth.zip](https://github.com/PGPAuth/PGPAuth_Android/files/984106/pgpauth.zip)

Could you try this version? (Play Store signed)

**Comment by DeX77** [comment] 2017-05-09 09:21
Yes, this works again. But now everything is no longer translated and as soon as I push "Lock" or "Unlock" I have to select the key to use: didn't have to do that before.

**Comment by LittleFox94** [comment] 2017-05-09 10:07
Yeah, translations are not included in that build but will be in final release.

Selecting a key is now required because the settings per app are gone in OpenKeychain. I will look into the new api, but this is more a feature than a bug.

Release will be this evening (CEST).

Thank you for testing :)

Am 9. Mai 2017 11:21:59 MESZ schrieb DeX77 <notifications@github.com>:
>Yes, this works again. But now everything is no longer translated and
>as soon as I push "Lock" or "Unlock" I have to select the key to use:
>didn't have to do that before.
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/PGPAuth/PGPAuth_Android/issues/18#issuecomment-300109170

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by LittleFox94** [comment] 2017-05-09 16:07
Will look into better key handling in issue #19, this issue is fixed with the new build currently going through the google play pipeline.

F-Droid Update may take longer, since it will be the first since the migration to Gradle/Android Studio.

**Closed by LittleFox94** 2017-05-09 16:07 UTC
Labels: bug
